-- Migration: account-recovery-moderator
-- Run against the Neon database via Neon console or npm run db:migrate

-- ── Part A: Security question columns on pw_users ─────────────────────────────
ALTER TABLE pw_users
  ADD COLUMN IF NOT EXISTS security_question VARCHAR(200),
  ADD COLUMN IF NOT EXISTS security_answer_hash VARCHAR(255);

-- ── Part B: Password reset tokens ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pw_password_reset_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES pw_users(id) ON DELETE CASCADE,
  token_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  request_ip VARCHAR(45)
);

-- Only one active (unused) token per user at a time
CREATE UNIQUE INDEX IF NOT EXISTS idx_pw_reset_tokens_active
  ON pw_password_reset_tokens(user_id) WHERE used = FALSE;

CREATE INDEX IF NOT EXISTS idx_pw_reset_tokens_user
  ON pw_password_reset_tokens(user_id, created_at DESC);

-- ── Part C: Moderator system ───────────────────────────────────────────────────

-- Moderator accounts
CREATE TABLE IF NOT EXISTS pw_moderators (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  invite_token_id UUID,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_login TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT TRUE
);

-- Invite tokens (generated by admin, consumed at activation)
CREATE TABLE IF NOT EXISTS pw_moderator_invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  used_by UUID REFERENCES pw_moderators(id),
  used_at TIMESTAMPTZ,
  label VARCHAR(100)
);

-- Moderator sessions (mirrors pw_user_sessions pattern)
CREATE TABLE IF NOT EXISTS pw_moderator_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  moderator_id UUID REFERENCES pw_moderators(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL
);

-- Moderator action log (preserves record even if mod is deleted via ON DELETE SET NULL)
CREATE TABLE IF NOT EXISTS pw_moderator_actions (
  id BIGSERIAL PRIMARY KEY,
  moderator_id UUID REFERENCES pw_moderators(id) ON DELETE SET NULL,
  moderator_username VARCHAR(50),
  action_type VARCHAR(50) NOT NULL,
  action_data JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pw_mod_sessions_mod    ON pw_moderator_sessions(moderator_id);
CREATE INDEX IF NOT EXISTS idx_pw_mod_actions_mod     ON pw_moderator_actions(moderator_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pw_mod_actions_recent  ON pw_moderator_actions(created_at DESC);
