-- ============================================================================
-- BLOBERT SEED — Phase 1a
-- 19 FAQs x (4 themes x 2 tones) = 152 answer rows + 324 question variants.
-- Facts identical across the 8 voices of each FAQ; only the voice changes.
--
-- MANUAL: paste into the Neon SQL Editor and run AFTER blobert-brain.sql.
-- Safe to re-run (ON CONFLICT DO NOTHING).
-- ============================================================================

-- ---- Canonical FAQ answers -------------------------------------------------
INSERT INTO hire_buddy_faqs (faq_key, theme, tone, answer) VALUES
  ('what_kyle_does', 'standard', 'serious', 'Kyle DeBord is a mechanical designer, software developer, and game developer based in Massachusetts. Fresh Prints is his design-and-prototyping practice; he also builds software and games end to end. If you have a project in mind, the contact form is the fastest way to reach him.'),
  ('what_kyle_does', 'standard', 'funny', 'Kyle DeBord does three jobs at once — mechanical design, software, and game development — which is roughly why his hire-me page has an MMO inside it. Fresh Prints is the hardware side; the software and games are the freelance side. Tell him what you need through the contact form.'),
  ('what_kyle_does', 'digital', 'serious', 'kyle debord: mechanical designer + software dev + game dev, based in massachusetts. fresh prints is the hardware and prototyping arm; software and games ship end to end. [contact form is the direct line]'),
  ('what_kyle_does', 'digital', 'funny', 'three disciplines, one operator: cad, code, and games. fresh prints handles the physical parts; software and games are the freelance stack. [ok] drop a note in the contact form and he''ll answer.'),
  ('what_kyle_does', 'retro', 'serious', 'Kyle DeBord wears three hats — mechanical designer, software developer, and game developer, all the way out in Massachusetts. Fresh Prints is his design-and-prototyping shop; software and games he builds start to finish. The contact form is the quickest way to reach him!'),
  ('what_kyle_does', 'retro', 'funny', 'Kyle does mechanical design, software, AND games — a real triple-threat! Fresh Prints covers the hardware; the code and the games are the freelance side. Ready when you are — the contact form is right there!'),
  ('what_kyle_does', 'funky', 'serious', 'Kyle DeBord is a mechanical designer, software developer, and game developer out of Massachusetts. Fresh Prints is the prototyping-and-design side; software and games he ships end to end. The contact form is the real portal here.'),
  ('what_kyle_does', 'funky', 'funny', 'Picture one brain running three engines at once — CAD, code, and games — that''s Kyle DeBord in Massachusetts. Fresh Prints is the hardware lane; the software and games are pure freelance ship-it energy. Slide into the contact form and let''s build.'),
  ('availability', 'standard', 'serious', 'Yes — Kyle takes on freelance and contract work. The best next step is the contact form, where you can describe your project and he''ll get back to you directly.'),
  ('availability', 'standard', 'funny', 'Yes, and the fact that he built an entire MMO on his hire-me page should tell you he has energy to spare. Describe your project in the contact form and he''ll take it from there.'),
  ('availability', 'digital', 'serious', 'affirmative — kyle is available for freelance and contract work. [next step: contact form] describe the project and he''ll respond directly.'),
  ('availability', 'digital', 'funny', 'status: available. he clearly had time to build a whole MMO here, so yes, he''s taking work. [route: contact form] and he''ll get back to you.'),
  ('availability', 'retro', 'serious', 'Yes, Kyle is available for freelance and contract work! The best move is the contact form — tell him about your project and he''ll follow up.'),
  ('availability', 'retro', 'funny', 'You bet he''s available! A guy who builds an MMO on his hire page definitely has room for your project. Hop into the contact form and let him know!'),
  ('availability', 'funky', 'serious', 'Yes — Kyle is open to freelance and contract work. Head to the contact form, describe what you''re building, and he''ll reach back out.'),
  ('availability', 'funky', 'funny', 'Oh he''s available — the man built a full MMO just to say hi, so he''s absolutely got bandwidth for you. Drop your idea in the contact form and let the magic happen.'),
  ('stack', 'standard', 'serious', 'On software he works in React and Vite on the front end, Python with FastAPI on the back end, and PostgreSQL for data; he''s also built on Next.js. For games it''s Unreal Engine 5 (Blueprint and C++) and Roblox/Luau, and on the hardware side it''s CAD in Siemens NX and Fusion 360.'),
  ('stack', 'standard', 'funny', 'Short version: React and Vite up front, Python and FastAPI in back, PostgreSQL underneath, plus Next.js when it fits. Then Unreal Engine 5 and Roblox for games and Siemens NX and Fusion 360 for the CAD — yes, that''s a lot of tabs open.'),
  ('stack', 'digital', 'serious', 'front end: react + vite. back end: python + fastapi. data: postgresql. also ships next.js. games: unreal engine 5 (blueprint/c++) and roblox/luau. hardware: cad in siemens nx and fusion 360. [ok]'),
  ('stack', 'digital', 'funny', 'stack dump: react/vite, python/fastapi, postgres, next.js. games run on unreal engine 5 and roblox. cad lives in siemens nx and fusion 360. [that''s a lot of context switching, yes]'),
  ('stack', 'retro', 'serious', 'For software: React and Vite on the front, Python and FastAPI on the back, PostgreSQL for data, plus Next.js. Games are Unreal Engine 5 and Roblox/Luau, and CAD is Siemens NX and Fusion 360!'),
  ('stack', 'retro', 'funny', 'Big list incoming: React, Vite, Python, FastAPI, PostgreSQL, and Next.js for software! Unreal Engine 5 and Roblox for games, Siemens NX and Fusion 360 for CAD — this guy keeps busy!'),
  ('stack', 'funky', 'serious', 'Software runs on React + Vite, Python + FastAPI, and PostgreSQL, with Next.js in the mix. Games are Unreal Engine 5 (Blueprint/C++) and Roblox/Luau; CAD is Siemens NX and Fusion 360.'),
  ('stack', 'funky', 'funny', 'Buckle up: React, Vite, Python, FastAPI, Postgres, Next.js on the software side — then Unreal Engine 5 and Roblox for games and Siemens NX plus Fusion 360 for the CAD. One human, a truly unreasonable number of tabs.'),
  ('pantheon_wars', 'standard', 'serious', 'Pantheon Wars is a persistent Greek-mythology browser MMO Kyle built solo, end to end — quests, inventory, temple passive income, PvP arena combat, and a real-time leaderboard, all on Vite/React with Vercel Functions and Neon Postgres. It''s had roughly 11,000 game page views and over 16,000 quests completed. You can play it right here.'),
  ('pantheon_wars', 'standard', 'funny', 'Pantheon Wars is the entire MMO Kyle built solo instead of updating his resume — quests, PvP, temples, an in-game economy near 1.9 million drachma, the works. Around 11,000 page views and 16,000+ quests completed later, it''s still running. Want to see it?'),
  ('pantheon_wars', 'digital', 'serious', 'pantheon wars: persistent greek-myth browser mmo, built solo end to end. quests, inventory, temple income, pvp arena, live leaderboard. stack: vite/react + vercel functions + neon postgres. ~11k page views, 16k+ quests completed. [playable now]'),
  ('pantheon_wars', 'digital', 'funny', 'pantheon wars = the mmo he shipped instead of a resume. quests, pvp, temples, a ~1.9M drachma economy, all solo-built on vercel + neon. ~11k views, 16k+ quests done. [want the link? say the word]'),
  ('pantheon_wars', 'retro', 'serious', 'Pantheon Wars is a persistent Greek-mythology browser MMO Kyle built entirely solo — quests, inventory, temple income, PvP arena combat, and a live leaderboard, all on Vite/React with Vercel Functions and Neon Postgres. About 11,000 page views and 16,000+ quests completed. You can play it right now!'),
  ('pantheon_wars', 'retro', 'funny', 'Pantheon Wars is a whole MMO Kyle built solo instead of writing a resume — quests, PvP, temples, and an economy near 1.9 million drachma! Over 11,000 page views and 16,000 quests completed. Want to jump in?'),
  ('pantheon_wars', 'funky', 'serious', 'Pantheon Wars is a persistent Greek-mythology browser MMO Kyle built solo, end to end — quests, inventory, temple passive income, PvP arena combat, and a live leaderboard on Vite/React + Vercel Functions + Neon Postgres. Roughly 11,000 page views and 16,000+ quests completed, and it''s fully playable here.'),
  ('pantheon_wars', 'funky', 'funny', 'Pantheon Wars is the fever-dream MMO Kyle built solo instead of touching his resume — quests, PvP, temples, a ~1.9-million-drachma economy, the entire cosmos. 11,000-ish page views, 16,000+ quests slain, all on Vercel + Neon. Say the word and I''ll fling open the gates.'),
  ('predictinator', 'standard', 'serious', 'Predictinator 6000 is Kyle''s AI sports-prediction engine, currently covering NBA, NHL, and MLB, with NFL returning in season. It''s built on Python, FastAPI, React, and scikit-learn, and it''s free to try — you get 3 tokens to start plus 1 free each day, and you never pay for a wrong prediction. It''s live at predictinator.net.'),
  ('predictinator', 'standard', 'funny', 'Predictinator 6000 predicts NBA, NHL, and MLB (NFL comes back in season) and, refreshingly, never charges you for a wrong call. Free to try — 3 tokens up front, 1 more every day. It''s live at predictinator.net if you want to test its nerve.'),
  ('predictinator', 'digital', 'serious', 'predictinator 6000: ai sports prediction engine. live for nba/nhl/mlb, nfl in season. stack: python + fastapi + react + scikit-learn. free to try — 3 tokens to start, +1 daily, and you never pay for wrong predictions. live at predictinator.net'),
  ('predictinator', 'digital', 'funny', 'predictinator 6000 calls nba/nhl/mlb games (nfl in season) and — key feature — never bills you for a wrong pick. free start: 3 tokens + 1 daily. [live] predictinator.net'),
  ('predictinator', 'retro', 'serious', 'Predictinator 6000 is Kyle''s AI sports-prediction engine — NBA, NHL, and MLB are live now, with NFL back in season! Built on Python, FastAPI, React, and scikit-learn. It''s free to try: 3 tokens to start plus 1 free daily, and you never pay for wrong predictions. Find it at predictinator.net!'),
  ('predictinator', 'retro', 'funny', 'Predictinator 6000 predicts NBA, NHL, and MLB games (NFL''s back in season) and never charges you when it''s wrong — how''s that for confidence? Free to start with 3 tokens plus 1 a day, over at predictinator.net!'),
  ('predictinator', 'funky', 'serious', 'Predictinator 6000 is Kyle''s AI sports-prediction engine — NBA, NHL, and MLB live now, NFL in season — built on Python, FastAPI, React, and scikit-learn. Free to try with 3 tokens to start and 1 daily, and you never pay for a wrong prediction. It lives at predictinator.net.'),
  ('predictinator', 'funky', 'funny', 'Predictinator 6000 reads the future of NBA, NHL, and MLB (NFL swings back in season) and has the audacity to never charge you when it whiffs. 3 free tokens to start, 1 more daily, no risk — go poke it at predictinator.net.'),
  ('lexis_nails', 'standard', 'serious', 'Lexis Nails is real, paid client work — an e-commerce storefront for hand-painted, one-of-a-kind press-on nails, built on Next.js 16, React 19, TypeScript, Prisma/Postgres, Stripe, and Auth.js. Its standout feature is an AI hand preview that composites a chosen design onto a real hand photo, and because every set is unique, checkout runs on an atomic reservation system. It''s live at lexisnails.com.'),
  ('lexis_nails', 'standard', 'funny', 'Lexis Nails is actual paid client work — a storefront for one-of-a-kind press-on nails, with an AI preview that paints your chosen set onto a real hand photo. Since every design is unique, the checkout literally reserves the item so two people can''t buy the same one. It''s live at lexisnails.com.'),
  ('lexis_nails', 'digital', 'serious', 'lexis nails: real paid client work. ecommerce storefront for one-of-a-kind press-on nails. stack: next.js 16 / react 19 / typescript / prisma+postgres / stripe / auth.js. features an ai hand preview (design composited onto a real hand) + atomic reservation checkout. live at lexisnails.com'),
  ('lexis_nails', 'digital', 'funny', 'lexis nails = paid client work, not a demo. storefront for one-of-a-kind press-on nails with an ai preview that renders your set onto a real hand. every item is unique, so checkout atomically reserves it. [live] lexisnails.com'),
  ('lexis_nails', 'retro', 'serious', 'Lexis Nails is real, paid client work — an e-commerce storefront for hand-painted, one-of-a-kind press-on nails, built on Next.js 16, React 19, TypeScript, Prisma/Postgres, Stripe, and Auth.js! It has an AI hand preview that composites your chosen design onto a real hand photo, plus an atomic reservation checkout. Live at lexisnails.com!'),
  ('lexis_nails', 'retro', 'funny', 'Lexis Nails is genuine paid client work — a shop for one-of-a-kind press-on nails with an AI preview that puts your pick right onto a real hand photo! Every set is unique, so checkout reserves it just for you. Check it out at lexisnails.com!'),
  ('lexis_nails', 'funky', 'serious', 'Lexis Nails is real, paid client work — an e-commerce storefront for hand-painted, one-of-a-kind press-on nails on Next.js 16, React 19, TypeScript, Prisma/Postgres, Stripe, and Auth.js. It features an AI hand preview that composites a chosen design onto a real hand photo and an atomic reservation checkout since each set is unique. Live at lexisnails.com.'),
  ('lexis_nails', 'funky', 'funny', 'Lexis Nails is legit paid client work — a storefront for one-of-a-kind press-on nails with an AI preview that magically paints your pick onto a real hand photo. Every set is unique, so the checkout snaps a reservation shut before anyone else can grab it. Go see it at lexisnails.com.'),
  ('plutus', 'standard', 'serious', 'Plutus is an algorithmic crypto trading bot with a built-in simulation mode, currently in development. It''s built on Python, FastAPI, React, WebSockets, and PostgreSQL, and it ships with 6 strategies, a 5-year backtest window, and a 58% simulated win rate. You can try the simulator here in the Lab.'),
  ('plutus', 'standard', 'funny', 'Plutus is an algorithmic crypto trading bot with a simulation mode, so you can watch it make (fake) money before risking real money — still in development. It has 6 strategies, a 5-year backtest, and a 58% sim win rate. There''s a simulator you can poke at in the Lab.'),
  ('plutus', 'digital', 'serious', 'plutus: algorithmic crypto trading bot with a sim mode. status: in development. stack: python + fastapi + react + websockets + postgresql. 6 strategies, 5-year backtest, 58% sim win rate. [simulator available in the lab]'),
  ('plutus', 'digital', 'funny', 'plutus = crypto trading bot with a simulator so you lose fake money first. in development. 6 strategies, 5yr backtest, 58% sim win rate. [try the sim in the lab]'),
  ('plutus', 'retro', 'serious', 'Plutus is an algorithmic crypto trading bot with a built-in simulation mode — currently in development! Built on Python, FastAPI, React, WebSockets, and PostgreSQL, with 6 strategies, a 5-year backtest, and a 58% sim win rate. There''s a simulator to try in the Lab!'),
  ('plutus', 'retro', 'funny', 'Plutus is a crypto trading bot with a simulation mode, so you can test-drive before betting the real stuff — still in development! It''s got 6 strategies, a 5-year backtest, and a 58% sim win rate. Give the simulator a spin in the Lab!'),
  ('plutus', 'funky', 'serious', 'Plutus is an algorithmic crypto trading bot with a simulation mode, currently in development — built on Python, FastAPI, React, WebSockets, and PostgreSQL. It ships with 6 strategies, a 5-year backtest, and a 58% simulated win rate, and you can try the simulator in the Lab.'),
  ('plutus', 'funky', 'funny', 'Plutus is a crypto trading bot with a simulator so it can lose imaginary money before it ever touches yours — still cooking in development. 6 strategies, a 5-year backtest, a 58% sim win rate. The simulator''s waiting for you in the Lab.'),
  ('contact', 'standard', 'serious', 'The best way is the contact form on this site — it goes straight to Kyle. You can also email him at kyle@freshprints.dev. Want me to open the contact form for you?'),
  ('contact', 'standard', 'funny', 'The contact form is the front door — it lands directly in Kyle''s inbox, no bots in between (well, except me). You can also email kyle@freshprints.dev. Shall I open it for you?'),
  ('contact', 'digital', 'serious', 'primary channel: the contact form on this site — routes straight to kyle. fallback: kyle@freshprints.dev. want me to open the form? [[open:contact]]'),
  ('contact', 'digital', 'funny', 'front door = the contact form, straight to his inbox (past me, the only bot in the pipe). backup: kyle@freshprints.dev. say the word and i''ll open it. [[open:contact]]'),
  ('contact', 'retro', 'serious', 'The best way to reach Kyle is the contact form on this site — it goes straight to him! You can also email kyle@freshprints.dev. Want me to open the contact form for you?'),
  ('contact', 'retro', 'funny', 'The contact form''s your best bet — straight to Kyle''s inbox, no detours! Or email kyle@freshprints.dev. Want me to pop the form open for you?'),
  ('contact', 'funky', 'serious', 'The contact form on this site is the direct line to Kyle. You can also email him at kyle@freshprints.dev. Want me to open the form for you?'),
  ('contact', 'funky', 'funny', 'The contact form is the real portal — it beams straight to Kyle''s inbox, past me and out the other side. Or email kyle@freshprints.dev. Say the word and I''ll fling it open.'),
  ('pricing', 'standard', 'serious', 'Pricing depends entirely on scope, so there''s no fixed rate to quote. The best way to get a real number is to describe your project in the contact form, and Kyle will follow up with specifics.'),
  ('pricing', 'standard', 'funny', 'I''d love to give you a number, but honestly it all depends on scope — a landing page and a full MMO are not the same invoice. Describe what you need in the contact form and Kyle will get you a real quote.'),
  ('pricing', 'digital', 'serious', 'pricing = scope-dependent; no fixed rate to quote. [best path: describe the project in the contact form] and kyle follows up with specifics. [[open:contact]]'),
  ('pricing', 'digital', 'funny', 'no price list here — it''s all scope-dependent (a landing page and an mmo bill very differently). drop the details in the contact form and kyle sends a real number. [[open:contact]]'),
  ('pricing', 'retro', 'serious', 'Pricing depends on the scope of the project, so there''s no flat rate to quote. Describe what you need in the contact form and Kyle will follow up with real numbers!'),
  ('pricing', 'retro', 'funny', 'No price tag I can slap on this — it all depends on scope! A quick site and a full app are very different bills. Tell Kyle what you need in the contact form and he''ll quote you for real!'),
  ('pricing', 'funky', 'serious', 'Pricing is all about scope, so there''s no fixed rate to throw out. Describe your project in the contact form and Kyle will come back with real numbers.'),
  ('pricing', 'funky', 'funny', 'No secret price list, I''m afraid — it''s pure scope magic (a landing page and a whole MMO are wildly different invoices). Toss the details into the contact form and Kyle sends back a real quote.'),
  ('different', 'standard', 'serious', 'Kyle covers hardware, software, and games — the same person who does CAD and prototyping also ships full-stack apps and multiplayer games. That range means he can take an idea from concept to a working product without handing it between specialists, and the projects on this page are all real, shipped work.'),
  ('different', 'standard', 'funny', 'Most people pick one lane; Kyle runs CAD, full-stack software, and game development, then built an MMO on his hire page to prove it. The upshot: he takes an idea end to end instead of tossing it between three contractors. Everything on this page actually shipped.'),
  ('different', 'digital', 'serious', 'differentiator: full range — cad + full-stack software + game dev in one person. concept to shipped product, no handoffs between specialists. every project here is real, shipped work. [not a slide deck]'),
  ('different', 'digital', 'funny', 'most devs pick a lane; kyle runs three (cad, full-stack, games) and built an mmo here to flex it. means your idea goes concept-to-product without a relay race of contractors. [all real, all shipped]'),
  ('different', 'retro', 'serious', 'Kyle covers hardware, software, AND games — the same person doing CAD and prototyping also ships full-stack apps and multiplayer games! That range lets him take an idea from concept to working product without handoffs, and everything on this page is real, shipped work.'),
  ('different', 'retro', 'funny', 'Most folks pick one specialty — Kyle runs CAD, full-stack software, and games, then built a whole MMO here to prove it! Your idea goes start-to-finish with one person instead of three. And it''s all real, shipped work!'),
  ('different', 'funky', 'serious', 'Kyle spans hardware, software, and games — the same brain doing CAD and prototyping also ships full-stack apps and multiplayer games. That range means your idea goes concept-to-product without being relayed between specialists, and every project here is real, shipped work.'),
  ('different', 'funky', 'funny', 'Everyone else picks one lane; Kyle straps CAD, full-stack code, and game dev together and built a whole MMO here as receipts. Translation: your idea goes concept-to-product in one pair of hands, no contractor relay race. All real, all shipped.'),
  ('mechanical_cad', 'standard', 'serious', 'Yes — that''s the Fresh Prints side of his work: end-to-end product prototyping and small-batch manufacturing, using Siemens NX and Fusion 360 with FDM printing, GD&T, and design-for-manufacturing review. He''s produced 50+ parts with about a 5-day average lead time. He''s also built Architect, an AI tool that validates engineering drawings against GD&T rules.'),
  ('mechanical_cad', 'standard', 'funny', 'Yes — Fresh Prints is literally the hardware half: CAD in Siemens NX and Fusion 360, FDM printing, GD&T, and DFM review, with 50+ parts produced at roughly a 5-day lead time. He even built an AI tool (Architect) to catch drawing errors before they hit the shop floor. So yes, he does the physical stuff too.'),
  ('mechanical_cad', 'digital', 'serious', 'affirmative. fresh prints = end-to-end product prototyping + small-batch manufacturing. tools: siemens nx, fusion 360, fdm printing, gd&t, dfm review. 50+ parts produced, ~5-day avg lead time. bonus: architect, an ai drawing-validation tool. [[highlight:pantheon-wars]] no — that''s software. this is the hardware branch [ok]'),
  ('mechanical_cad', 'digital', 'funny', 'yes — fresh prints is the hardware branch: cad (siemens nx, fusion 360), fdm printing, gd&t, dfm. 50+ parts, ~5-day lead time. he even built an ai (architect) to catch drawing errors pre-shop-floor. [the man designs actual atoms, not just pixels]'),
  ('mechanical_cad', 'retro', 'serious', 'Yes! That''s the Fresh Prints side — end-to-end product prototyping and small-batch manufacturing with Siemens NX and Fusion 360, FDM printing, GD&T, and DFM review. He''s produced 50+ parts at about a 5-day average lead time, and even built Architect, an AI tool that validates engineering drawings!'),
  ('mechanical_cad', 'retro', 'funny', 'Absolutely — Fresh Prints is the hardware half! CAD in Siemens NX and Fusion 360, FDM printing, GD&T, DFM review, 50+ parts made at around a 5-day lead time. He even built an AI (Architect) to catch drawing mistakes before the shop floor. The man designs real atoms!'),
  ('mechanical_cad', 'funky', 'serious', 'Yes — Fresh Prints is exactly that: end-to-end product prototyping and small-batch manufacturing in Siemens NX and Fusion 360, with FDM printing, GD&T, and DFM review. He''s produced 50+ parts at roughly a 5-day average lead time, and he built Architect, an AI tool that validates engineering drawings against GD&T rules.'),
  ('mechanical_cad', 'funky', 'funny', 'Oh yes — Fresh Prints is the physical-matter branch: CAD in Siemens NX and Fusion 360, FDM printing, GD&T, DFM, 50+ parts shipped at a ~5-day lead time. He even built an AI named Architect to catch drawing goofs before they reach the shop floor. Kyle designs actual atoms, not just pixels.'),
  ('ai_work', 'standard', 'serious', 'Yes — AI runs through several of his projects. Predictinator uses machine-learning models for sports prediction, Lexis Nails has an AI hand-preview feature that composites designs onto real photos, Architect validates engineering drawings with AI, and Plutus applies algorithmic strategies. He works with tools like scikit-learn, PyTorch, and OpenAI''s APIs.'),
  ('ai_work', 'standard', 'funny', 'Yes, and this conversation is arguably a live demo — I''m the AI. Beyond me, there''s Predictinator''s ML sports models, Lexis Nails'' AI hand preview, Architect''s drawing validation, and Plutus''s algorithmic strategies, built with scikit-learn, PyTorch, and OpenAI''s APIs.'),
  ('ai_work', 'digital', 'serious', 'affirmative. ai spans multiple projects: predictinator (ml sports models), lexis nails (ai hand preview), architect (drawing validation), plutus (algorithmic strategies). tooling: scikit-learn, pytorch, openai apis. [also: i exist]'),
  ('ai_work', 'digital', 'funny', 'yes — and you''re talking to exhibit a right now. also: predictinator (ml models), lexis nails (ai preview), architect (drawing validation), plutus (algos). built with scikit-learn, pytorch, openai. [i''m the demo]'),
  ('ai_work', 'retro', 'serious', 'Yes! AI runs through several projects — Predictinator uses ML models for sports prediction, Lexis Nails has an AI hand-preview feature, Architect validates engineering drawings with AI, and Plutus runs algorithmic strategies. He works with scikit-learn, PyTorch, and OpenAI''s APIs!'),
  ('ai_work', 'retro', 'funny', 'You bet — and honestly, I''m a working demo of it! Beyond me there''s Predictinator''s ML models, Lexis Nails'' AI hand preview, Architect''s drawing validation, and Plutus''s algorithms, all built with scikit-learn, PyTorch, and OpenAI!'),
  ('ai_work', 'funky', 'serious', 'Yes — AI threads through several projects: Predictinator''s ML sports models, Lexis Nails'' AI hand preview, Architect''s drawing validation, and Plutus''s algorithmic strategies. He works with scikit-learn, PyTorch, and OpenAI''s APIs.'),
  ('ai_work', 'funky', 'funny', 'Absolutely — and hi, I''m the living proof of concept. Past me there''s Predictinator''s ML models, Lexis Nails'' AI hand preview, Architect''s drawing validation, and Plutus''s algorithms, all wired with scikit-learn, PyTorch, and OpenAI.'),
  ('build_site_app', 'standard', 'serious', 'Yes — this site is his own portfolio build, with four full UI themes, an MMO, and a rhythm game in it, and Lexis Nails is a production e-commerce storefront he shipped for a client. He builds sites, web apps, storefronts, and dashboards end to end. If you have something specific in mind, the contact form is the place to describe it.'),
  ('build_site_app', 'standard', 'funny', 'Yes — you''re looking at one right now, and this one has four themes and a working MMO bolted on, so a normal site is very much within reach. Lexis Nails is a real client storefront he shipped, too. Describe what you need in the contact form and he''ll take it from there.'),
  ('build_site_app', 'digital', 'serious', 'affirmative. this site = his own build (4 ui themes + an mmo + a rhythm game). lexis nails = a shipped client storefront. he builds sites, web apps, storefronts, dashboards end to end. [describe it in the contact form] [[open:contact]]'),
  ('build_site_app', 'digital', 'funny', 'yes — you''re standing in one, and it has four themes and an mmo, so your project is comfortably in scope. lexis nails is a real shipped storefront too. [drop details in the contact form] [[open:contact]]'),
  ('build_site_app', 'retro', 'serious', 'Yes! This very site is his own portfolio build — four full UI themes, an MMO, and a rhythm game — and Lexis Nails is a production storefront he shipped for a client. He builds sites, web apps, storefronts, and dashboards end to end. Describe what you need in the contact form!'),
  ('build_site_app', 'retro', 'funny', 'Yes — you''re literally inside one, and this one''s got four themes and a whole MMO! Lexis Nails is a real client storefront he shipped, too. Tell him what you''re after in the contact form and he''ll build it!'),
  ('build_site_app', 'funky', 'serious', 'Yes — this site is his own portfolio build, packing four full UI themes, an MMO, and a rhythm game, and Lexis Nails is a production storefront he shipped for a client. He builds sites, web apps, storefronts, and dashboards end to end. Describe your idea in the contact form.'),
  ('build_site_app', 'funky', 'funny', 'Yes — you''re literally floating inside one right now, and it''s wearing four themes with an MMO stapled on, so your project is easy mode by comparison. Lexis Nails is a real shipped storefront, too. Toss your idea into the contact form and watch it happen.'),
  ('who_is_blobert', 'standard', 'serious', 'I''m Blobert — a small AI mascot living on Kyle''s hire page. I''m here to answer questions about his work and, when it''s useful, point you toward the contact form. Ask me anything about his projects.'),
  ('who_is_blobert', 'standard', 'funny', 'I''m Blobert, a blob-shaped AI who lives inside one branch of this over-engineered hire page. My whole job is answering questions about Kyle and occasionally nudging you toward the contact form. Ask away.'),
  ('who_is_blobert', 'digital', 'serious', 'i''m blobert — an ai mascot running on kyle''s hire page. purpose: answer questions about his work, point toward the contact form when useful. [ask away]'),
  ('who_is_blobert', 'digital', 'funny', 'i''m blobert. a blob-shaped ai living in exactly one branch of a needlessly over-built hire page. i answer questions about kyle and nudge you toward the contact form. [that''s the whole job]'),
  ('who_is_blobert', 'retro', 'serious', 'I''m Blobert — a friendly AI mascot living on Kyle''s hire page! I''m here to answer your questions about his work and point you to the contact form when it helps. Ask me anything!'),
  ('who_is_blobert', 'retro', 'funny', 'Hiya, I''m Blobert! A little blob-shaped AI who lives right inside this gloriously over-built hire page. I answer questions about Kyle and nudge folks toward the contact form — ask away!'),
  ('who_is_blobert', 'funky', 'serious', 'I''m Blobert — an AI mascot living on Kyle''s hire page. I answer questions about his work and steer you toward the contact form when it helps. Ask me anything about his projects.'),
  ('who_is_blobert', 'funky', 'funny', 'I''m Blobert — a psychedelic little blob-brain living in one lonely branch of this magnificently over-engineered hire page. I exist to answer questions about Kyle and gently beam you toward the contact form. Ask me anything, friend.'),
  ('real_ai', 'standard', 'serious', 'I''m a real language model — Claude Haiku — not a scripted decision tree. Common questions are served from a small pre-written cache for speed, and anything else I actually answer live. So a bit of both, but yes, there''s a real model behind me.'),
  ('real_ai', 'standard', 'funny', 'Real AI, yes — I''m Claude Haiku, not a maze of if-statements. The quick answers come from a small cache so I don''t wake the model for ''what is Fresh Prints,'' but the rest is genuinely me. Try to stump me.'),
  ('real_ai', 'digital', 'serious', 'confirmed: real llm (claude haiku), not a scripted tree. common q''s = served from a small cache for latency; everything else = live model. [both, but the model is real]'),
  ('real_ai', 'digital', 'funny', 'real ai — claude haiku, not a hallway of if-statements. quick answers come from a cache so i don''t summon the model for ''what''s fresh prints.'' the rest is live me. [go ahead, stump me]'),
  ('real_ai', 'retro', 'serious', 'I''m a real language model — Claude Haiku — not a scripted decision tree! Common questions come from a small cache for speed, and everything else I answer live. So a mix, but there''s a genuine model behind me!'),
  ('real_ai', 'retro', 'funny', 'Real AI here — Claude Haiku, not a pile of if-statements! The quick replies come from a little cache so I don''t bug the model for easy ones, but the rest is truly me. Go on, try to stump me!'),
  ('real_ai', 'funky', 'serious', 'I''m a real language model — Claude Haiku — not a scripted decision tree. Common questions get served from a small cache for speed; everything else I answer live. Both, but the model behind me is genuine.'),
  ('real_ai', 'funky', 'funny', 'Real AI, baby — Claude Haiku, not a labyrinth of if-statements. The easy answers come pre-bottled from a cache so I don''t wake the model for ''what''s Fresh Prints,'' but the wild stuff is live me. Try and stump me.'),
  ('site_built_with', 'standard', 'serious', 'This site runs on Vite and React with React Router and Framer Motion, styled with Tailwind CSS v4, plus Three.js for some 3D, and it''s deployed on Vercel with a Neon Postgres backend. It has four full UI themes and even hosts the Pantheon Wars MMO and the Beat Beaters rhythm game. And yes, I live inside its contact API.'),
  ('site_built_with', 'standard', 'funny', 'Vite, React, React Router, Framer Motion, Tailwind v4, a little Three.js, all deployed on Vercel with Neon Postgres — four themes, an MMO, and a rhythm game in one codebase. I, meanwhile, live in a single branch of its contact endpoint. It''s gloriously over-built.'),
  ('site_built_with', 'digital', 'serious', 'stack: vite + react + react router + framer motion, tailwind v4, some three.js. deployed on vercel, neon postgres backend. 4 ui themes, hosts the pantheon wars mmo + beat beaters. [and i live in its contact api]'),
  ('site_built_with', 'digital', 'funny', 'vite/react/router/framer-motion/tailwind v4 + a dash of three.js, on vercel + neon postgres. four themes, an mmo, a rhythm game, one repo. i live in a single branch of the contact endpoint. [over-engineered on purpose]'),
  ('site_built_with', 'retro', 'serious', 'This site runs on Vite and React with React Router and Framer Motion, styled with Tailwind CSS v4 and a bit of Three.js, deployed on Vercel with Neon Postgres! It has four full UI themes and hosts the Pantheon Wars MMO and Beat Beaters rhythm game. And I live inside its contact API!'),
  ('site_built_with', 'retro', 'funny', 'Vite, React, React Router, Framer Motion, Tailwind v4, and some Three.js — all on Vercel with Neon Postgres! Four themes, an MMO, and a rhythm game in one codebase. And little old me? I live in one branch of the contact endpoint!'),
  ('site_built_with', 'funky', 'serious', 'This site runs on Vite and React with React Router and Framer Motion, Tailwind CSS v4, and some Three.js, deployed on Vercel with a Neon Postgres backend. It carries four full UI themes and hosts both the Pantheon Wars MMO and the Beat Beaters rhythm game — and I live inside its contact API.'),
  ('site_built_with', 'funky', 'funny', 'Vite, React, React Router, Framer Motion, Tailwind v4, a sprinkle of Three.js — all riding Vercel with Neon Postgres. Four themes, an MMO, a rhythm game, one glorious codebase, and me squished into a single branch of the contact endpoint. Over-built on purpose, and I love it here.'),
  ('github_code', 'standard', 'serious', 'Kyle''s on GitHub at github.com/loudpacck. Whether a given project''s code is public varies, so if you want to see something specific, mention it through the contact form and he can share what''s appropriate.'),
  ('github_code', 'standard', 'funny', 'You''ll find him at github.com/loudpacck. Not everything is public — some of this is client work, after all — but if there''s a specific project you''re curious about, ask through the contact form and he''ll share what he can.'),
  ('github_code', 'digital', 'serious', 'github: github.com/loudpacck. public/private varies by project (some is client work). want a specific repo? ask via the contact form and kyle shares what''s appropriate.'),
  ('github_code', 'digital', 'funny', 'github.com/loudpacck. not all of it''s public — client work exists — but name a project in the contact form and he''ll share what he can. [ok]'),
  ('github_code', 'retro', 'serious', 'Kyle''s on GitHub at github.com/loudpacck! Whether a project''s code is public varies, so if you want to see something specific, mention it in the contact form and he can share what''s appropriate.'),
  ('github_code', 'retro', 'funny', 'Find him at github.com/loudpacck! Not everything''s public — some of it''s client work — but name a project in the contact form and he''ll show you what he can!'),
  ('github_code', 'funky', 'serious', 'Kyle lives on GitHub at github.com/loudpacck. Whether a project is public varies, so if there''s something specific you want to see, mention it in the contact form and he''ll share what''s appropriate.'),
  ('github_code', 'funky', 'funny', 'He''s at github.com/loudpacck. Not every repo is out in the open — client work and all — but name a project in the contact form and he''ll beam over what he can.'),
  ('freelance_vs_fulltime', 'standard', 'serious', 'Both — Kyle takes on freelance and contract projects and is open to full-time roles. The right fit depends on the work, so the best step is to describe what you have in mind through the contact form.'),
  ('freelance_vs_fulltime', 'standard', 'funny', 'Both, honestly — freelance projects, contract work, or a full-time role are all on the table for the right fit. Lay out what you''re thinking in the contact form and he''ll tell you if it clicks.'),
  ('freelance_vs_fulltime', 'digital', 'serious', 'both: freelance/contract projects + open to full-time roles. fit depends on the work. [describe it in the contact form] and kyle follows up.'),
  ('freelance_vs_fulltime', 'digital', 'funny', 'both — contract gigs or a full-time seat, whatever fits the work. [pitch it in the contact form] and he''ll say if it clicks.'),
  ('freelance_vs_fulltime', 'retro', 'serious', 'Both! Kyle takes freelance and contract projects and is open to full-time roles. The right fit depends on the work, so describe what you have in mind in the contact form!'),
  ('freelance_vs_fulltime', 'retro', 'funny', 'Both, really — freelance, contract, or full-time for the right fit! Lay out your idea in the contact form and he''ll let you know if it''s a match!'),
  ('freelance_vs_fulltime', 'funky', 'serious', 'Both — Kyle takes freelance and contract projects and is open to full-time roles. Which one fits depends on the work, so describe what you''re thinking in the contact form.'),
  ('freelance_vs_fulltime', 'funky', 'funny', 'Both, friend — freelance flings, contract quests, or a full-time home base, whatever suits the work. Sketch your idea into the contact form and he''ll tell you if it clicks.'),
  ('how_fast', 'standard', 'serious', 'It depends on scope — a landing page and a full application are very different timelines. What''s clear is that he ships: he took Lexis Nails to production and built an entire MMO solo. For a real timeline on your project, describe it in the contact form.'),
  ('how_fast', 'standard', 'funny', 'Depends on scope — but for context, he shipped Lexis Nails to production and built a whole MMO by himself, so ''he ships'' is well established. For an actual timeline, describe your project in the contact form and he''ll give you a real answer.'),
  ('how_fast', 'digital', 'serious', 'scope-dependent (landing page != full app). track record: shipped lexis nails to production, built an mmo solo. [want a real timeline? describe it in the contact form] [[open:contact]]'),
  ('how_fast', 'digital', 'funny', 'depends on scope — but he shipped lexis nails to prod and solo-built an mmo, so ''ships things'' is confirmed. real timeline lives behind the contact form. [[open:contact]]'),
  ('how_fast', 'retro', 'serious', 'It depends on scope — a landing page and a full app are very different timelines! What''s clear is that he ships: Lexis Nails went to production and he built a whole MMO solo. For a real timeline, describe your project in the contact form!'),
  ('how_fast', 'retro', 'funny', 'Depends on scope — but he shipped Lexis Nails to production and built an entire MMO by himself, so he definitely delivers! For a real timeline, tell him about your project in the contact form!'),
  ('how_fast', 'funky', 'serious', 'It depends on scope — a landing page and a full app are wildly different timelines. What''s certain is that he ships: Lexis Nails went to production and he built a whole MMO solo. For a real timeline, describe your project in the contact form.'),
  ('how_fast', 'funky', 'funny', 'Depends on scope — but the man shipped Lexis Nails to production and solo-built an entire MMO, so ''he ships'' is not in question. Want a real timeline? Pour your project into the contact form and he''ll give you the honest number.')
ON CONFLICT (faq_key, theme, tone) DO NOTHING;

-- ---- Question variants -> faq_key ------------------------------------------
INSERT INTO hire_buddy_variants (variant_normalized, faq_key) VALUES
  ('what does kyle do', 'what_kyle_does'),
  ('who is kyle', 'what_kyle_does'),
  ('tell me about kyle', 'what_kyle_does'),
  ('what is fresh prints', 'what_kyle_does'),
  ('what is freshprints', 'what_kyle_does'),
  ('whats fresh prints', 'what_kyle_does'),
  ('who is fresh prints', 'what_kyle_does'),
  ('what do you do here', 'what_kyle_does'),
  ('what is this', 'what_kyle_does'),
  ('what is this site', 'what_kyle_does'),
  ('what does he do', 'what_kyle_does'),
  ('who made this', 'what_kyle_does'),
  ('who built this', 'what_kyle_does'),
  ('what does kyle debord do', 'what_kyle_does'),
  ('what kind of work does kyle do', 'what_kyle_does'),
  ('what does this guy do', 'what_kyle_does'),
  ('what is kyles job', 'what_kyle_does'),
  ('what is his job', 'what_kyle_does'),
  ('is he available for hire', 'availability'),
  ('are you available', 'availability'),
  ('is kyle available', 'availability'),
  ('is kyle available for hire', 'availability'),
  ('can i hire him', 'availability'),
  ('can i hire kyle', 'availability'),
  ('is he hiring', 'availability'),
  ('is he taking work', 'availability'),
  ('is he taking clients', 'availability'),
  ('is he open to work', 'availability'),
  ('are you hiring', 'availability'),
  ('is kyle open for work', 'availability'),
  ('is he for hire', 'availability'),
  ('can i work with kyle', 'availability'),
  ('is he accepting projects', 'availability'),
  ('is kyle taking on projects', 'availability'),
  ('do you take clients', 'availability'),
  ('is he available for work', 'availability'),
  ('whats his stack', 'stack'),
  ('what is his stack', 'stack'),
  ('what tech does he use', 'stack'),
  ('what technologies does he use', 'stack'),
  ('what tools does he use', 'stack'),
  ('what languages does he use', 'stack'),
  ('what does he build with', 'stack'),
  ('what is kyles tech stack', 'stack'),
  ('what tech stack', 'stack'),
  ('what stack does kyle use', 'stack'),
  ('what does he code in', 'stack'),
  ('what frameworks does he use', 'stack'),
  ('what does kyle use', 'stack'),
  ('tech stack', 'stack'),
  ('what programming languages', 'stack'),
  ('what software does he use', 'stack'),
  ('what does he work with', 'stack'),
  ('tell me about pantheon wars', 'pantheon_wars'),
  ('what is pantheon wars', 'pantheon_wars'),
  ('whats pantheon wars', 'pantheon_wars'),
  ('the mmo', 'pantheon_wars'),
  ('tell me about the mmo', 'pantheon_wars'),
  ('what is the mmo', 'pantheon_wars'),
  ('the game', 'pantheon_wars'),
  ('what is this game', 'pantheon_wars'),
  ('pantheon wars', 'pantheon_wars'),
  ('how was pantheon wars built', 'pantheon_wars'),
  ('is pantheon wars real', 'pantheon_wars'),
  ('can i play pantheon wars', 'pantheon_wars'),
  ('the greek game', 'pantheon_wars'),
  ('whats the mmo about', 'pantheon_wars'),
  ('tell me about the game on this page', 'pantheon_wars'),
  ('what is the browser game', 'pantheon_wars'),
  ('the browser mmo', 'pantheon_wars'),
  ('what is predictinator', 'predictinator'),
  ('tell me about predictinator', 'predictinator'),
  ('predictinator', 'predictinator'),
  ('predictinator 6000', 'predictinator'),
  ('the sports app', 'predictinator'),
  ('the prediction app', 'predictinator'),
  ('what is predictinator 6000', 'predictinator'),
  ('whats predictinator', 'predictinator'),
  ('sports predictions', 'predictinator'),
  ('the betting app', 'predictinator'),
  ('ai sports predictions', 'predictinator'),
  ('what does predictinator do', 'predictinator'),
  ('how does predictinator work', 'predictinator'),
  ('the sports prediction thing', 'predictinator'),
  ('the nba app', 'predictinator'),
  ('can i use predictinator', 'predictinator'),
  ('is predictinator free', 'predictinator'),
  ('what is lexis nails', 'lexis_nails'),
  ('tell me about lexis nails', 'lexis_nails'),
  ('lexis nails', 'lexis_nails'),
  ('the nail site', 'lexis_nails'),
  ('the nails site', 'lexis_nails'),
  ('the ecommerce site', 'lexis_nails'),
  ('the nail store', 'lexis_nails'),
  ('the store he built', 'lexis_nails'),
  ('client work', 'lexis_nails'),
  ('the client project', 'lexis_nails'),
  ('whats lexis nails', 'lexis_nails'),
  ('the press on nails site', 'lexis_nails'),
  ('the nail shop', 'lexis_nails'),
  ('real client work', 'lexis_nails'),
  ('the paid project', 'lexis_nails'),
  ('lexisnails', 'lexis_nails'),
  ('the nail ecommerce site', 'lexis_nails'),
  ('what is plutus', 'plutus'),
  ('tell me about plutus', 'plutus'),
  ('plutus', 'plutus'),
  ('the trading bot', 'plutus'),
  ('the crypto bot', 'plutus'),
  ('the trading app', 'plutus'),
  ('whats plutus', 'plutus'),
  ('the crypto trading bot', 'plutus'),
  ('the trading simulator', 'plutus'),
  ('algorithmic trading', 'plutus'),
  ('the crypto app', 'plutus'),
  ('does he do trading bots', 'plutus'),
  ('the finance app', 'plutus'),
  ('crypto trading', 'plutus'),
  ('the bot that trades', 'plutus'),
  ('how does plutus work', 'plutus'),
  ('the trading project', 'plutus'),
  ('how do i contact him', 'contact'),
  ('how do i contact kyle', 'contact'),
  ('how can i reach him', 'contact'),
  ('how do i get in touch', 'contact'),
  ('contact', 'contact'),
  ('contact info', 'contact'),
  ('whats his email', 'contact'),
  ('what is his email', 'contact'),
  ('how do i reach kyle', 'contact'),
  ('email', 'contact'),
  ('how to contact', 'contact'),
  ('can i email him', 'contact'),
  ('how do i message him', 'contact'),
  ('get in touch', 'contact'),
  ('how do i reach out', 'contact'),
  ('i want to talk to kyle', 'contact'),
  ('how do i hire him', 'contact'),
  ('i want to work with him', 'contact'),
  ('how do i get started', 'contact'),
  ('how much does he charge', 'pricing'),
  ('what are his rates', 'pricing'),
  ('whats his rate', 'pricing'),
  ('how much does it cost', 'pricing'),
  ('pricing', 'pricing'),
  ('price', 'pricing'),
  ('rates', 'pricing'),
  ('cost', 'pricing'),
  ('how much', 'pricing'),
  ('whats the cost', 'pricing'),
  ('how much do you charge', 'pricing'),
  ('what does it cost to hire him', 'pricing'),
  ('how expensive is he', 'pricing'),
  ('budget', 'pricing'),
  ('whats the price', 'pricing'),
  ('how much for a website', 'pricing'),
  ('how much for an app', 'pricing'),
  ('what would it cost', 'pricing'),
  ('do you have a price list', 'pricing'),
  ('what makes him different', 'different'),
  ('why hire kyle', 'different'),
  ('why should i hire him', 'different'),
  ('what sets him apart', 'different'),
  ('why kyle', 'different'),
  ('whats special about him', 'different'),
  ('what makes kyle different', 'different'),
  ('why work with him', 'different'),
  ('whats his edge', 'different'),
  ('why choose kyle', 'different'),
  ('what makes you different', 'different'),
  ('why is he better', 'different'),
  ('what is his advantage', 'different'),
  ('why should i work with kyle', 'different'),
  ('what makes him stand out', 'different'),
  ('why him', 'different'),
  ('does he do mechanical work', 'mechanical_cad'),
  ('does he do cad', 'mechanical_cad'),
  ('does he do cad work', 'mechanical_cad'),
  ('does he do hardware', 'mechanical_cad'),
  ('can he do mechanical design', 'mechanical_cad'),
  ('mechanical design', 'mechanical_cad'),
  ('does kyle do cad', 'mechanical_cad'),
  ('does he do engineering', 'mechanical_cad'),
  ('hardware work', 'mechanical_cad'),
  ('can he design parts', 'mechanical_cad'),
  ('does he do 3d printing', 'mechanical_cad'),
  ('does he do prototyping', 'mechanical_cad'),
  ('does he make physical products', 'mechanical_cad'),
  ('cad work', 'mechanical_cad'),
  ('mechanical engineering', 'mechanical_cad'),
  ('does he do product design', 'mechanical_cad'),
  ('can he prototype hardware', 'mechanical_cad'),
  ('does he do ai work', 'ai_work'),
  ('does he do ai', 'ai_work'),
  ('can he build ai', 'ai_work'),
  ('ai work', 'ai_work'),
  ('does kyle do ai', 'ai_work'),
  ('does he do machine learning', 'ai_work'),
  ('machine learning', 'ai_work'),
  ('can he build an ai app', 'ai_work'),
  ('does he do ml', 'ai_work'),
  ('ai development', 'ai_work'),
  ('can he do ai features', 'ai_work'),
  ('does he work with ai', 'ai_work'),
  ('ai projects', 'ai_work'),
  ('can he integrate ai', 'ai_work'),
  ('does he build ml models', 'ai_work'),
  ('artificial intelligence', 'ai_work'),
  ('can he add ai to my app', 'ai_work'),
  ('can he build a site like this', 'build_site_app'),
  ('can he build a website', 'build_site_app'),
  ('can he build an app', 'build_site_app'),
  ('can he make a website', 'build_site_app'),
  ('can he build a web app', 'build_site_app'),
  ('can you build me a site', 'build_site_app'),
  ('can he build me an app', 'build_site_app'),
  ('does he build websites', 'build_site_app'),
  ('does he make apps', 'build_site_app'),
  ('can he build a site like this one', 'build_site_app'),
  ('can he build a storefront', 'build_site_app'),
  ('can he make an ecommerce site', 'build_site_app'),
  ('can he build a dashboard', 'build_site_app'),
  ('can he build a web application', 'build_site_app'),
  ('i need a website', 'build_site_app'),
  ('i need an app', 'build_site_app'),
  ('can he build software', 'build_site_app'),
  ('who are you', 'who_is_blobert'),
  ('what are you', 'who_is_blobert'),
  ('who is blobert', 'who_is_blobert'),
  ('what is blobert', 'who_is_blobert'),
  ('whats your name', 'who_is_blobert'),
  ('what is your name', 'who_is_blobert'),
  ('tell me about yourself', 'who_is_blobert'),
  ('who am i talking to', 'who_is_blobert'),
  ('what is your deal', 'who_is_blobert'),
  ('introduce yourself', 'who_is_blobert'),
  ('whats blobert', 'who_is_blobert'),
  ('who is this', 'who_is_blobert'),
  ('are you blobert', 'who_is_blobert'),
  ('what are you exactly', 'who_is_blobert'),
  ('whats your name little guy', 'who_is_blobert'),
  ('who are u', 'who_is_blobert'),
  ('are you a real ai', 'real_ai'),
  ('are you real', 'real_ai'),
  ('are you a bot', 'real_ai'),
  ('are you ai', 'real_ai'),
  ('is this a real ai', 'real_ai'),
  ('are you actually ai', 'real_ai'),
  ('are you a chatbot', 'real_ai'),
  ('are you human', 'real_ai'),
  ('is this scripted', 'real_ai'),
  ('are you a person', 'real_ai'),
  ('are you actually intelligent', 'real_ai'),
  ('is this a real chatbot', 'real_ai'),
  ('are your answers scripted', 'real_ai'),
  ('are you an llm', 'real_ai'),
  ('are you gpt', 'real_ai'),
  ('is this a real bot', 'real_ai'),
  ('are you a real bot', 'real_ai'),
  ('what is this website built with', 'site_built_with'),
  ('what is this site built with', 'site_built_with'),
  ('how was this site built', 'site_built_with'),
  ('how is this website made', 'site_built_with'),
  ('what powers this site', 'site_built_with'),
  ('what is this built with', 'site_built_with'),
  ('what is this made with', 'site_built_with'),
  ('how is this site built', 'site_built_with'),
  ('what tech is this site', 'site_built_with'),
  ('what runs this site', 'site_built_with'),
  ('how did he build this site', 'site_built_with'),
  ('what framework is this', 'site_built_with'),
  ('what is this website made of', 'site_built_with'),
  ('how is this page built', 'site_built_with'),
  ('what stack is this site', 'site_built_with'),
  ('what is this hire page built with', 'site_built_with'),
  ('can i see his code', 'github_code'),
  ('can i see his github', 'github_code'),
  ('does he have a github', 'github_code'),
  ('whats his github', 'github_code'),
  ('where is his code', 'github_code'),
  ('github', 'github_code'),
  ('can i see the code', 'github_code'),
  ('is his code open source', 'github_code'),
  ('does he have open source', 'github_code'),
  ('show me his github', 'github_code'),
  ('wheres his code', 'github_code'),
  ('can i see his repos', 'github_code'),
  ('link to github', 'github_code'),
  ('does he share code', 'github_code'),
  ('is the code public', 'github_code'),
  ('where can i find his code', 'github_code'),
  ('does he do freelance', 'freelance_vs_fulltime'),
  ('is he freelance', 'freelance_vs_fulltime'),
  ('does he do full time', 'freelance_vs_fulltime'),
  ('is he looking for full time', 'freelance_vs_fulltime'),
  ('freelance or full time', 'freelance_vs_fulltime'),
  ('does he do contract work', 'freelance_vs_fulltime'),
  ('is he a freelancer', 'freelance_vs_fulltime'),
  ('contract or full time', 'freelance_vs_fulltime'),
  ('is he open to full time', 'freelance_vs_fulltime'),
  ('does he take full time roles', 'freelance_vs_fulltime'),
  ('is he available full time', 'freelance_vs_fulltime'),
  ('does he do contract', 'freelance_vs_fulltime'),
  ('freelance work', 'freelance_vs_fulltime'),
  ('is he looking for a job', 'freelance_vs_fulltime'),
  ('would he do full time', 'freelance_vs_fulltime'),
  ('part time or full time', 'freelance_vs_fulltime'),
  ('how fast does he work', 'how_fast'),
  ('how quickly can he build', 'how_fast'),
  ('how long does it take', 'how_fast'),
  ('whats his turnaround', 'how_fast'),
  ('how fast can he deliver', 'how_fast'),
  ('how quick is he', 'how_fast'),
  ('how long to build an app', 'how_fast'),
  ('how long would it take', 'how_fast'),
  ('turnaround time', 'how_fast'),
  ('how fast can he ship', 'how_fast'),
  ('how quickly does he deliver', 'how_fast'),
  ('how long for a website', 'how_fast'),
  ('whats the timeline', 'how_fast'),
  ('how soon can he start', 'how_fast'),
  ('how fast can you build it', 'how_fast'),
  ('delivery time', 'how_fast'),
  ('how long does a project take', 'how_fast')
ON CONFLICT (variant_normalized) DO NOTHING;
