export default {
  id: 'pantheon',
  label: 'Pantheon',
  status: 'complete',
  navigation: 'hub',
  hasSoundFx: false,
  soundPack: null,
  layoutType: 'game',
  supportsLightMode: false,
  supportsDarkMode: true,
  defaultMode: 'dark',
  hidden: true,
  comingSoon: true,
  fonts: {
    display: 'Cinzel',
    body: 'Cormorant Garamond',
    mono: 'IBM Plex Mono',
  },
  tagline: 'Mythological grandeur.',
  description: 'Ornate obsidian and gold. WotLK era meets pan-mythology.',
  palette: ['#0A0710', '#14101A', '#C9A961', '#F5D88B', '#EDE3CC'],
}
